### ISSUE TITLE
pc端运行之后没有反应，大神给看看呗

### ISSUE THREAD

**Issue by joleyii** [BinsonZoom/BCastScreen#1]
C:\Users\123>java -jar C:\Users\123\Desktop\luping\BCastScreen.jar
start init!
com.android.ddmlib.AndroidDebugBridge@279f2327
found:null,8400503444243c0f018d
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
make IContainer!

**Comment by joleyii** [comment]
当时就有了，忘了关了

**Comment by BinsonZoom** [comment]
其实你用我这个做录屏功能是完全够用的，如果想要更流畅castScreen，更好的解决方案，请google minicap，基于c层实现。
